require "pogger.colorscheme"
require "pogger.indent"
require "pogger.keymaps"
require "pogger.lsp"
require "pogger.lualine"
require "pogger.nvimtree"
require "pogger.options"
require "pogger.plugins"
require "pogger.telescope"
require "pogger.term"
require "pogger.treesitter"

